# -*- coding: utf-8 -*-
"""counting_words.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/171Z-4zd8TPywY0-y96mrH548ZLSgcVFm
"""

words = ("AI is being tested and used in the healthcare industry for suggesting drug dosages, identifying treatments, and for aiding in surgical procedures in the operating room.")

words = words.split()

words

words_count = {}

for word in words:
  words_count[word] = words_count.get(word , 0) + 1
print(words_count)