# -*- coding: utf-8 -*-
"""arsenal_players.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lWE4nFrYYdu4Wr5kW8ETwi8l-vgpMcNl
"""

#capitalise players name
arsenal_players = ("bukayo saka" , "gabriel jesus" ,"william saliba" , "declan rice")
arsenal_players = [name.title() for name in arsenal_players]
print(arsenal_players)

#display players names each per line
for name in arsenal_players:
  print(name)
print ("done!") # print done! once finished displaying players names.